# Default values for optima.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
webapp:
account:
payoutplan:
offer:

auth:
  enabled: true

  replicaCount: 1

  imagePullSecrets: []

  image:
    repository: gcr.io/project1-153912/optima-v1/authentication
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart version.
    tag: "latest"

  nameOverride: "optima-auth"
  fullnameOverride: "optima-auth"

  environment:
    - name: PORT  #Container Inside port on which application will be running
      value: 3000
    - name: dbService
      value: "http://db/dbService"

  service:
    type: ClusterIP
    port: 80
    containerPort: 3000 #Value must be same with the above defined env var "PORT"

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: "sa-optima-auth"

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths: []
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

db:
  enabled: true

  replicaCount: 1

  imagePullSecrets: []

  image:
    repository: gcr.io/project1-153912/optima-v1/db
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart version.
    tag: "latest"

  nameOverride: "optima-db"
  fullnameOverride: "optima-db"

  environment:
    - name: PORT  #Container Inside port on which application will be running
      value: 3000

  service:
    type: ClusterIP
    port: 80
    containerPort: 3000 #Value must be same with the above defined env var "PORT"

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: "sa-optima-db"

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths: []
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}