{{- if .Values.account.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "optima.account.serviceAccountName" . }}
  labels:
    {{- include "optima.account.labels" . | nindent 4 }}
  {{- with .Values.account.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
