{{- if .Values.offer.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "optima.offer.serviceAccountName" . }}
  labels:
    {{- include "optima.offer.labels" . | nindent 4 }}
  {{- with .Values.offer.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
