{{- if .Values.payout.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "optima.payout.fullname" . }}
  labels:
    {{- include "optima.payout.labels" . | nindent 4 }}
spec:
  type: {{ .Values.payout.service.type }}
  ports:
    - port: {{ .Values.payout.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "optima.payout.selectorLabels" . | nindent 4 }}
{{- end }}