{{- if .Values.payout.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "optima.payout.serviceAccountName" . }}
  labels:
    {{- include "optima.payout.labels" . | nindent 4 }}
  {{- with .Values.payout.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
